{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'good' in 'hello world'", "trace": "@allure.feature('模块二')\n    @allure.story('这厮一个很niu的测试用例')\n    def test_4():\n        \"\"\"\n        这是对函数的参数，返回值的一个注释\n    \n        \"\"\"\n        # 测试用例的描述是是通过注释获取到的\n>       assert \"good\" in \"hello world\"\nE       AssertionError: assert 'good' in 'hello world'\n\ntest_allure.py:46: AssertionError"}, "description": "\n    这是对函数的参数，返回值的一个注释\n\n    ", "start": 1566181558823, "stop": 1566181558824, "uuid": "e664e517-d58a-4d5d-9227-23e829477642", "historyId": "a069be209cd5870321eb818addbaf83c", "fullName": "test_allure#test_4", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这厮一个很niu的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "Caizhanyang"}, {"name": "thread", "value": "14492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}