{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "def test_3():\n>       assert 2 == 3\nE       assert 2 == 3\n\ntest_allure.py:22: AssertionError"}, "start": 1566179278724, "stop": 1566179278724, "uuid": "d7c118ac-5430-4451-b1c8-478dab2260b8", "historyId": "5afd0dda8524db6b29be91008b13a69f", "fullName": "test_allure#test_3", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "Caizhanyang"}, {"name": "thread", "value": "6792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}