{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "def test_3():\n>       assert 2 == 3\nE       assert 2 == 3\n\ntest_allure.py:36: AssertionError"}, "start": 1566181558762, "stop": 1566181558762, "uuid": "e96d7e22-c61e-4f85-a326-16646ff41fa1", "historyId": "5afd0dda8524db6b29be91008b13a69f", "fullName": "test_allure#test_3", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "Caizhanyang"}, {"name": "thread", "value": "14492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}